### ISSUE TITLE
[Bug]: Winget does not run

### ISSUE THREAD

**Issue by CodeDoctorDE** [LinwoodCloud/Butterfly#214]
### What happened?

The winget job does not run.
@vedantmgoyal2009 can you please look at it?

### Version

-

### Platform

Windows

### Relevant log output

```shell
https://github.com/LinwoodCloud/Butterfly/actions/runs/2675056491
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
```
Found Existing Version: 1.4.0-rc.3
  Exception: D:\a\Butterfly\Butterfly\winget-pkgs\Tools\YamlCreate.ps1:919
  Line |
   919 |      Throw 'Number of InstallerUrls are not equal'
       |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       | Number of InstallerUrls are not equal
  
  node:child_process:826
      err = new Error(msg);
            ^
  
  Error: Command failed: .\YamlCreate.ps1 '{"PackageIdentifier":"LinwoodCloud.Butterfly.Nightly","PackageVersion":"1.5.0-alpha.1","InstallerUrls":[],"ReleaseNotesUrl":"https://github.com/LinwoodCloud/Butterfly/releases/tag/v1.5.0-alpha.1","ReleaseDate":"2022-09-02","DeletePreviousVersion":false}'
      at checkExecSyncError (node:child_process:826:11)
      at execSync (node:child_process:900:15)
      at D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:9123:3
      at D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:9129:3
      at D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:9131:3
      at Object.<anonymous> (D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:9134:12)
      at Module._compile (node:internal/modules/cjs/loader:1101:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1[153](https://github.com/LinwoodCloud/Butterfly/runs/8158849194?check_suite_focus=true#step:3:155):10)
      at Module.load (node:internal/modules/cjs/loader:981:32)
      at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
    status: 1,
    signal: null,
    output: [ null, null, null ],
    pid: 2664,
    stdout: null,
    stderr: null
  }
```

**Comment by CodeDoctorDE** [comment]
```
Found Existing Version: 1.4.0-rc.3
  Exception: D:\a\Butterfly\Butterfly\winget-pkgs\Tools\YamlCreate.ps1:919
  Line |
   919 |      Throw 'Number of InstallerUrls are not equal'
       |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       | Number of InstallerUrls are not equal
  
  node:child_process:826
      err = new Error(msg);
            ^
  
  Error: Command failed: .\YamlCreate.ps1 '{"PackageIdentifier":"LinwoodCloud.Butterfly.Nightly","PackageVersion":"1.5.0-alpha.1","InstallerUrls":[],"ReleaseNotesUrl":"https://github.com/LinwoodCloud/Butterfly/releases/tag/v1.5.0-alpha.1","ReleaseDate":"2022-09-02","DeletePreviousVersion":false}'
      at checkExecSyncError (node:child_process:826:11)
      at execSync (node:child_process:900:15)
      at D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:9123:3
      at D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:9129:3
      at D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:9131:3
      at Object.<anonymous> (D:\a\_actions\vedantmgoyal2009\winget-releaser\latest\dist\index.js:9134:12)
      at Module._compile (node:internal/modules/cjs/loader:1101:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1[153](https://github.com/LinwoodCloud/Butterfly/runs/8158849194?check_suite_focus=true#step:3:155):10)
      at Module.load (node:internal/modules/cjs/loader:981:32)
      at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
    status: 1,
    signal: null,
    output: [ null, null, null ],
    pid: 2664,
    stdout: null,
    stderr: null
  }
```
@vedantmgoyal2009
